- package.json
@andreGarvin @whyn07m3 check it out. 
jsdoc-template should not be in the critical path for installation.
> Removed jsdoc-template from critical path for install.

- package-lock.json
This updates the marked dependency in JS Docs which is currently set @ ~0.3.6 in our package-lock.json.
I was able to run the build command and give the ~ this should be fine.
> Update to marked 0.3.9 after github warning

- src/transport/transport-errors.ts
- src/transport/transport.ts
NoCorrelation Errors should not exist.
> RUN-3949 Fixed issue where no correlation errors were thrown when use d along side the legacy API.

- package-lock.json
- package.json
- src/api/plugin/plugin.ts
- test/multi-runtime-utils.ts
This PR is to update the config that multi runtime tests use.  Currently we enable v2api by default, but the config that these tests use is not updated.
> RUN-3999 multi runtime tests config update

- src/api/fin.ts
- src/api/services/channel.ts
- src/api/services/client.ts
- src/api/services/index.ts
- src/api/services/provider.ts
- src/transport/transport.ts
> RUN-4017/services

- src/transport/transport.ts
Websocket connects differently that IPC such that this rawSend was losing context and failing. Need this fix for external-adapters to work.
> bind rawsend

- src/api/plugin/plugin.ts
- test/plugin.test.ts
- tutorials/Plugin.import.md
ℹ️ PR's changes: fin.Plugin.import accepts a string instead of an object
**Chained with these PRs:**
⛓ [core PR](https://github.com/HadoukenIO/core/pull/396)
⛓ [javascript-adapter PR](https://github.com/openfin/javascript-adapter/pull/425)
> RUN-4033 plugin.import accepts a string

- Gruntfile.js
- src/api/base.ts
- src/launcher/nix-launch.ts
- src/launcher/util.ts
- src/util/normalize-config.ts
- src/util/promises.ts
- test/launcher.test.ts
- test/multi-runtime-utils.ts
- test/port-discovery.test.ts
Had an issue in the webpack task where errors were not being reported correctly. Once that was fixed I was able to see the error:
Base was importing functions from launcher/utils and webpack could not pack `fs` and `child_process`. So I moved the utils functions to the utils folder.
> Fixed issue with the webpack grunt task where it was not reporting the errors correctly

- test/external-services.test.ts
Remove usage of launch for tests, create and run app as normal.
> Simplify External Services Tests

- src/api/base.ts
- test/event-emitter.test.ts
rawListeners and eventNames not supported on the webpack emitter, so removing altogether.
Tests from within the runtime:
[Win 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5afde43a4ecc2a37d5a486cc)
[Win 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5afde58a4ecc2a37d5a486cd)
> Restricted the Event emitter functions we expose to match the exact set exposed by the webpack emitter.

- src/api/base.ts
TSC was throwing an error for a clean repo, because `type` as a symbol couldn't be converted to a string
> fixed typescript error

- src/api/global-hotkey/index.ts
- test/global-hotkey.test.ts
Fix a bug where unregisterAll would also remove event listeners for 'registered' and 'unregistered' events.
> Fixed unregister all bug.

- src/api/base.ts
- src/api/interappbus/channel/client.ts
- src/api/interappbus/channel/index.ts
- src/transport/transport.ts
- test/external-channel.test.ts
- test/multi-runtime-application.test.ts
- test/multi-runtime-channel.test.ts
See [Core PR](https://github.com/HadoukenIO/core/pull/508)
Moved pending channel connections into js-adapter.  
- If channel does not yet exist, core nacks back with interimNack message. Then we listen for connection event with correct UUID (later to be include name &/or channelName) and will resend the connect message -where it can be routed to correct runtime via normal mesh middleware.
- better handles lifecycle of request (if entity that made request closes, navigates, reloads etc.)
- better to implement multi-runtime channel connection with eventing / existing middleware
Had to fix some tests to make them all pass.  Added another multi-runtime test that was failing prior to these changes.
[Win7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5b60f0a854b21953031f388d …
> RUN-4342 - Multi-runtime channels

- Gruntfile.js
- README.md
the `test` task automatically runs the `core` task, this is not always what you need. 
Made the `core` task opt in by argument.
> Core builds should be optional.

- html/client.html
- html/service.html
- src/api/base.ts
- src/api/interappbus/channel/index.ts
- src/api/interappbus/channel/provider.ts
- test/external-channel.test.ts
- test/multi-runtime-channel.test.ts
Ability to create multiple channels for a single application.  Must use a channelName when you create a channel and you connect to channel by a channelName as well.  ChannelNames will be unique and creation will fail if you provide a name that is not unique.
[Core PR](https://github.com/HadoukenIO/core/pull/524)
Updated all channel related tests, plus there are six new testrunner tests and the additional js-adapter test in the code change:
[one](https://testing-dashboard.openfin.co/#/app/tests/5b7599ab6107b45e6d1eba2b/edit)
[two](https://testing-dashboard.openfin.co/#/app/tests/5b759e5a6107b45e6d1eba32/edit)
[three](https://testing-dashboard.openfin.co/#/app/tests/5b75d86c6107b45e6d1eba3e/edit)
[four](https://testing-dashboard.openfin.co/#/app/tests/5b75d9e56107b45e6d1eba3f/edit) …
> RUN-4331 - Multiple channels by channelName

- src/api/system/system.ts
- test/system.test.ts
- tutorials/System.getDeviceId.md
This won't make sense without #174
> RUN-4494: Deprecate System.getDeviceId() for System.getMachineId()

- src/api/window/window.ts
This reapplies the fix from https://github.com/HadoukenIO/js-adapter/commit/7f39a926e70d08cdf12424d785b71b28cba627a7
It also applies it to wrap sync. This avoids conflict based on the version bumps that have followed.
> Fixed window wrap and wrapSync

- src/api/window/window.ts
- tutorials/Window.getSnapshot.md
ℹ️ **About**
This and related PRs add support for taking snapshots of an area in a window.
🔗 All linked PRs
1\. [core PR](https://github.com/HadoukenIO/core/pull/561)
2\. [javascript-adapter PR](https://github.com/openfin/javascript-adapter/pull/500)
3\. [js-adapter PR](https://github.com/HadoukenIO/js-adapter/pull/188)
➕ **New automated tests**
1\. [window.getSnapshot (specified area)](https://testing-dashboard.openfin.co/#/app/tests/5ba1497ad6d66a0ddf8e7253/edit)
2\. [window.getSnapshot (specified area) (V2 API)](https://testing-dashboard.openfin.co/#/app/tests/5baa700ecb360141a7dfcf5f/edit)
🚥 **Test results**
✅ [Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5baa75bbcb360141a7dfcf65)
✅ Node test results
> RUN-2315 added support for taking a snapshot of an area in a window

- src/api/interappbus/channel/index.ts
- src/api/interappbus/channel/provider.ts
Adding onDisconnection and cleaning up channel.connections on a disconnect.
[new testrunner](https://testing-dashboard.openfin.co/#/app/tests/5b56102154b21953031f37a7/edit)
[Win7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bb3e9cecb360141a7dfcffe)
[Win10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bb3eafdcb360141a7dfd000)
> RUN-4443 - Channel Lifecycle / onDisconnection

- src/api/application/application.ts
- test/application.test.ts
- tutorials/Application.setAppLogUsername.md
Added a Core API with (action: "application-log-username"). Sends a message over the RVM bus that updates App Log username when uploaded.
Ex)
var app = fin.Application.getCurrent();
app.then(a => a.setAppLogUsername('test-username')).then( ()=>console.log('success'));
> RUN-4712 Add API to associate app log with custom username

- src/api/system/system.ts
- test/system.test.ts
This PR is adding the function to handle listener callback in System.launchExternalProcess function. 
[New Test](https://testing-dashboard.openfin.co/#/app/tests/5be097f6cb360141a7dfd1fb/edit)
> RUN-4730 listener callback not implemented in launchExternalProcess

- src/api/base.ts
Have fixed this bug a few times.  [core offending code](https://github.com/HadoukenIO/core/blob/develop/src/browser/remote_subscriptions.ts#L213).
Test results:
[Win7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5c1051c8cb360141a7dfd662)
[Win10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5c105322cb360141a7dfd663)
> Fixed issue where the core would use these function within events

- src/api/application/application.ts
- tutorials/Application.sendApplicationLog.md
Added sendApplicationLog API.
Returns a promise with the logId stored in the Log Manager.
> RUN-4834 Updated Ack to send logId in a data payload

- src/api/application/application.ts
- src/api/window/window.ts
Doc changes with the following:
V1 style Application options on the create `create` function
V1 style Window options on the create `create` function
"*DO NOT USE!* Use `create`" warning on Application/Window constructors.
> Doc changes for Options and constructor warning.

- docs.README.md
- src/api/application/application.ts
This PR adds api calls to start/quit an application. These calls replace create/run/close and clean up core state. The old methods are undocumented and now have a deprecation warning but will need to be made private/removed in future prs. Needs a core pr which adds a call to clean up core state.
> RUN-4644 Add calls to start/quit application

- Gruntfile.js
- test/multi-runtime-utils.ts
This PR removed useless flag: --enable-multi-runtime. Instead, we use --enable-mesh to achieve it and use --security-realm alone to disable mesh.
> RUN-4974 remove --enable-multi-runtime flag

- src/api/window/window.ts
- src/environment/environment.ts
- src/environment/node-env.ts
- src/environment/openfin-env.ts
- tutorials/Window.getWebWindow.md
Added the ability to get the [Window Object](https://developer.mozilla.org/en-US/docs/Web/API/Window) previously available in the V1 API as `getNativeWindow`
- [ X ] PR description included and stakeholders cc'd
- [ X ] `npm test` passes
- [ X ] automated tests are [changed or added](https://testing-dashboard.openfin.co/#/app/dashboard)
- [] manual tests are [changed or added](https://github.com/openfin/test_apps)
Notes: 
Added `getWebWindow` API that returns the [Window Object](https://developer.mozilla.org/en-US/docs/Web/API/Window).  Previously `getNativeWindow` in API V1
Test Results: 
[Win 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5c9e79c1cb360141a7dfdf3a)
[Win 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5c9e7c0acb360141a7dfdf3b)
> RUN-5123 getWebWindow

- src/util/http.ts
It looks like the URL module is implicitly imported in Node 10. Adding the import so it will work with versions prior to Node 10.
> Explicitly Import URL Module

- test/multi-runtime-utils.ts
- test/uuid-enforcement.test.ts
Related JIRA ticket:
https://appoji.jira.com/browse/RUN-5134
Tests are mostly taken from https://github.com/HadoukenIO/js-adapter/pull/229/files, but a test case has been added for the RUN-5134 functionality.
Only significant change to @pbaize's test setup is that I switched from using a server to loading app manifests from the file system. This appears to be working consistently, while the server setup was frequently timing out when performing multiple app manifest updates.
> RUN-5134 Add tests for UUID enforcement

- src/api/window/window.ts
Jira ticket: https://appoji.jira.com/browse/RUN-5182
Currently failing test that will pass with this change: https://testing-dashboard.openfin.co/#/app/tests/5cc20dbccb360141a7dfe17e/edit
Without this change, the js-adapter throws an error when attempting to create a window with the uuid and name of a pre-existing window. With this change, that error is passed back to the caller, allowing application code to handle it.
Note: I think `Min version` should probably be set in my dashboard test, but I'm not sure what it should be set to. Any pointers on that front much appreciated.
> RUN-5182: reject win creation errors to caller

- src/api/system/external-process.ts
- src/api/system/system.ts
- tutorials/getServiceConfiguration.md
This adds the ability to request service configurations found in the desktop owner settings file.
It is linked to [this core pr](https://github.com/HadoukenIO/core/pull/773). 
Note: this requires [this](https://github.com/openfin/openfinrvm/commit/57cc300a3989feb6e5324d53b8f13059f68b5328) RVM change to be released
> RUN-5222 get service configuration

- src/api/events/application.ts
This PR adds the bounds property to the `tray-icon-clicked` to match the shape of the event.
> [N/A] Add bounds to TrayIconClicked event

- test/multi-runtime-utils.ts
JIRA: https://appoji.jira.com/browse/RUN-5316
Was able to repro failing test by reducing RAM allocation for my VM to 2gb.
Appears to be a timing issue: if killing the rvm process has not finished before we attempt to delete the cache, we get an EPERM error. Switching to rimraf's async api fixes the issue (it automatically retries a few times if the first attempt fails).
Would appreciate if a couple people could pull this branch and run locally just to make sure the issue is fixed. Consistently works on my machine, but I was not initially seeing the failure either.
> RUN-5316: Fix failing uuid-enforcement test

- src/api/window/window.ts
- tutorials/Window.moveBy.md
- tutorials/Window.moveTo.md
- tutorials/Window.resizeBy.md
- tutorials/Window.resizeTo.md
- tutorials/Window.setBounds.md
- tutorials/Window.showAt.md
Associated with this `core` PR: https://github.com/HadoukenIO/core/pull/780
JIRA Ticket: https://appoji.jira.com/browse/RUN-5071
**[RUN-5071] Add option to window resize/movement APIs to allow windows to move independently of their group**
**Description:**
When we call the move/resize APIs for grouped windows, we now add a `moveIndependently` option in the options object for that call. If that option is set to `true`, we move that window independently of the rest of its group.
**Questions:**
Automated tests for all functions have been added to the `testing-dashboard`, but are currently private. When should I make them public? 
Not sure how linting is handled for the js-adapter? I formatted it according to the rest of the surrounding code.
Should I also add in the relevant code …
> [RUN-5071] Add option to window resize/movement APIs to allow windows to move independently of their group

- package-lock.json
- package.json
- test/window.test.ts
Updated typescript and had to change the tests do to a change in asserting truthiness on void.
Bumps to the same typescript version as the  [the core](https://github.com/HadoukenIO/core/pull/812).
Does this need a release note as far as definitely typed?
> RUN-5254 updated typescript to 3.5

- test/external-connection.test.ts
Linked to this PR: https://github.com/HadoukenIO/core/pull/841
Tests that an external connection can set its `name` property by passing it in the connection payload when it connects to a `Channel`. 
Do not merge until the core PR has been merged.
> [RUN-5208] Add test for external connections and nameAlias

- src/api/application/application.ts
- src/api/window/window.ts
This fixes a bug where the incorrect order of arguments in `Object.assign({}, ...)` would cause an override of `this.identity` if `name` or `uuid` are passed as options.
> RUN-5286 v2 Api SetBounds will override identity if passed in bounds have a name.

- .gitignore
- src/api/frame/frame.ts
- src/environment/environment.ts
- src/environment/node-env.ts
- src/environment/openfin-env.ts
- src/environment/openfin-renderer-api.ts
- src/transport/transport.ts
- test/assets/frame.html
- test/frame.test.ts
As per description of the issue:
"When calling getCurrentSync().getInfo the identity object returned should not share the name of the host window. This appears only to be broken in the v2  api. We need to make sure that the name returned matches the actual name (a guid produced by the runtime) that is used for routing."
This PR ensures that correct frame identity is used when initializing and working with iframes.
@rdepena  @datamadic @pbaize
> RUN-5382  Iframe names are incorrect with the v2 api

- tutorials/Window.getInfo.md
The PR documents the proposed `isUserMovementEnabled` field in `window.getInfo()` for users to be able to tell programmatically whether user movement is enabled
Test: https://testing-dashboard.openfin.co/#/app/tests/5d48843a394bc65e455b9a6e/edit
Notes: Added `isUserMovementEnabled` property to `window.getInfo()` that allows to programmatically discover whether user movement is enabled
> RUN-5456 There’s no way of programmatically telling if a window has enabled or disabled user movement

- src/api/browserview/browserview.ts
Enable multiple browser views per window. Allow re-attaching views to different windows
Notes:
> RUN-5449 Multi Browser View

- src/api/system/installed-runtimes.ts
- src/api/system/system.ts
- tutorials/System.getInstalledRuntimes.md
Added API for user to query the RVM for the versions of all the runtimes installed.
Compatible with RVM 5.3+
fin.system.getInstalledRuntimes( )
> [RVM-946] Added GetInstalledRuntimes api

- src/api/interappbus/channel/client.ts
Channel onDisconnection from the provider (on client disconnection) was not working multi-runtime. This PR makes it work.  The services team needs this for notifications. 
Goes with [this Core PR](https://github.com/HadoukenIO/core/pull/935)
Notes: Fixed bug where channel onDisconnection from the provider was not working across runtimes.
> RUN-5584 - Multi-runtime onDisconnection from ChannelProvider
