HadoukenIO/js-adapter

README.md

Also added missing clone/install instructions.

Clarify app developers vs. adapter developers

---

.gitmodules
package.json

@andreGarvin @whyn07m3 check it out.

fixed submodules to use git url and added update remote to post install script

---

package.json

@whyn07m3 @andreGarvin 
Noticed we were not using the right template.

using the OpenFin jsDoc template

---

.gitmodules
package.json

Fixed issue with npm install on windows.

---

package.json

Removed postbuild: tsc by mistake.

---

src/api/notification/notification.ts
src/api/window/window.ts

Added _Notification and _Window aliases for docs

---

README.md

set documentation link in the readme

---

test/multi-runtime.test.ts

removed some old multi runtime tests.

removed some old multi runtime tests

---

Gruntfile.js
test/multi-runtime-application.test.ts
test/multi-runtime-events.test.ts
test/multi-runtime-interappbus.test.ts
test/multi-runtime-utils.ts
test/multi-runtime-window.test.ts
test/multi-runtime.test.ts

@datamadic @whyn07m3 check it out.

added standard timeouts for multi runtime tests.

---

test/application.test.ts
test/system.test.ts
test/window.test.ts

fixed some of the bugs in the test for System and Application API

---

test/multi-runtime-system.test.ts
test/multi-runtime-utils.ts

Tests for multi-runtime system calls for:
- getAllApplications
- getAllExternalApplications
- getAllWindows
- getProcessList

Multi-runtime System Call Tests

---

package-lock.json
src/api/application/application.ts
src/api/clipboard/clipboard.ts
src/api/external-application/external-application.ts
src/api/interappbus/interappbus.ts
tutorials/Application.getParentUuid.md
tutorials/Application.getWindow.md
tutorials/Application.setShortcuts.md
tutorials/Clipboard.readHtml.md
tutorials/Clipboard.readText.md
tutorials/System.getHostSpecs.md
tutorials/Window.stopNavigation.md

add option property
make tutorials log functions consistent

add missing type

---

src/launcher/launcher.ts
src/launcher/nix-launch.ts
src/launcher/win-launch.ts
src/main.ts
src/transport/port-discovery.ts
src/transport/transport.ts
src/transport/wire.ts
src/util/normalize-config.ts
test/multi-runtime-utils.ts
test/port-discovery.test.ts

Made some changes in how the adapter uses external configs. Also export a "launch" function which launches an app with connecting.

Changes needed for the CLI

---

Gruntfile.js
test/application.test.ts
test/connect.ts
test/multi-runtime-events.test.ts
test/multi-runtime-utils.ts
test/window.test.ts

This PR is mainly fixing failed tests and cache deleting issue. 
Now all the tests passed against stable version. (8.56.27.75)

Fix failed tests and cache deleting issue

---

test/application.test.ts

This PR fixed two failed unit tests: getShortcuts and setShortcuts.

Enable some failed unit tests

---

Gruntfile.js
test/application.test.ts
test/launcher.test.ts
test/multi-runtime-utils.ts
test/multi-runtime.test.ts
test/port-discovery.test.ts

Also Skipping a number of tests that did not have any cleanup, will need to come back and fix.

Switching back to launching runtimes directly for multi-runtime tests.

---

src/api/notification/notification.ts
src/main.ts
test/notification.test.ts
tutorials/Notification.sendMessage.md
tutorials/Notification.show.md

This PR did some codes refactoring and correcting.

RUN-3968 Notification functions refactoring

---

src/transport/transport.ts

@pbaize @licui3936 @rdepena 
This temporarily stashes the reject of a wire send from ferryAction. If the connection drops before the call returns, any pending ferried api calls are nacked and removed from the map. 
Tests well locally.

RUN-3831 nack all pending ferried api called on dropped connection

---

jsdoc-conf.json
src/api/base.ts
src/api/fin.ts
src/api/plugin/plugin.ts
src/environment/environment.ts
src/environment/node-env.ts
src/environment/openfin-env.ts
src/main.ts
src/transport/port-discovery.ts
test/plugin.test.ts
tutorials/Plugin.import.md

⚠️ This PR is meant for OpenFin **v9**, however, it can still be consumed for v8 as well
ℹ️ **About**
This PR adds new Plugin API together with its docs
**js-adapter tests:**
✅ No new regressions - same errors as in latest master

RUN-3889 RUN-3961 added Plugin API with docs

---

Gruntfile.js
test/connect.ts

the openfin task was responsible of creating the app.json file under the test folder, bringing that back as well as removing the use of port discovery on the tests as mocha will time out before we are able to connect.
did a fresh clone and tested fine.

RUN-3972 Fixed tests.

---

src/api/system/runtime-info.ts
src/api/system/system.ts
test/system.test.ts
tutorials/System.getRuntimeInfo.md

This PR is adding a missing function getRuntimeInfo in js-adapter.

RUN-3971 Add getRuntimeInfo api to js-adapter

---

src/api/plugin/plugin.ts

✅ Node tests: no new regressions
✅ [Automated tests Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5ac3b31c4ecc2a37d5a483d5)

RUN-3996 multi-runtime regression fix

---

package-lock.json
package.json
src/api/plugin/plugin.ts

* RUN-3996 fixed a multi-runtime regression (#109)
* Version bump to 30.2

V bump.30.2 (#110)

---

src/environment/openfin-env.ts

This PR is to sync with javascript-adapter. 
Tests: 
[windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5ae21e9b4ecc2a37d5a4853d)
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5ae220834ecc2a37d5a4853e)

RUN-4045 register window name early in creation

---

.gitignore
html/client.html
html/service.html
src/api/services/client.ts
test/external-services.test.ts

Tests related to [Core PR](https://github.com/HadoukenIO/core/pull/383) that enables external applications to use services as client or provider.

RUN-3898 - External services tests

---

test/external-services.test.ts

Fixed test to work with flow of other tests.

Test fixed, no longer leaving around runtime

---

.gitignore
src/transport/port-discovery.ts
test/launch-services.test.ts

This includes tests for [this PR](https://github.com/HadoukenIO/core/pull/421) and makes port discovery happen on a per-connection basis.

Run-4140/adapter changes

---

test/interappbus.test.ts
tutorials/InterApplicationBus.subcribe.md

[RUN-4097](https://appoji.jira.com/browse/RUN-4097)  is not a bug.   The parameter signature for IAB has some change in V2 API.

RUN-4097 update IAB test and tutorial to include wildcard case

---

src/api/fin.ts
src/main.ts
src/of-main.ts

This PR just removes the token property in Fin object.

RUN-4206 Remove token property

---

src/api/application/application.ts
src/api/window/window.ts
src/environment/environment.ts
src/environment/node-env.ts
src/environment/openfin-env.ts
test/window.test.ts
tutorials/Window.getNativeWindow.md

This PR is adding native window.

RUN-4212 native window missing

---

test/multi-runtime-utils.ts

Whether these tests actually pass is an entirely different matter (that
isn't my problem for now), but at least these tests now point to the
correct directories when running on OS X.

Fix utils for multi-runtime tests on OS X

---

src/api/window/window.ts
test/window.test.ts

Add a new getGroup test for cross multiple applications

RUN-4226 fix window getGroup issue

---

src/api/application/application.ts
test/application.test.ts

Add a new getGroups test for cross multiple applications

RUN-4320 Fix application getGroups issue when there are different applications

---

package-lock.json
package.json
tsconfig.json

Updated typescript to 2.9 with target es2017

updated typescript

---

package.json

Was causing some wonkyness on local runtime/core builds. 
@aziz512 @pbaize Does this look ok to you guys?

moved the shell js dep to dev

---

src/api/application/application.ts
test/application.test.ts
tutorials/Application.getZoomLevel.md
tutorials/Application.setZoomLevel.md

This PR should combine with [core PR](https://github.com/HadoukenIO/core/pull/520).

RUN-4153 add two new APIs to application: setZoomLevel and getZoomLevel

---

src/api/system/system.ts
test/system.test.ts
tutorials/System.getMachineId.md

[JIRA](https://appoji.jira.com/browse/RUN-4438)
https://github.com/HadoukenIO/core/pull/532
https://github.com/openfin/javascript-adapter/pull/487
https://github.com/openfin/runtime/pull/1134

RUN-4438: System.getMachineId()

---

src/api/base.ts

ℹ️This PR introduces 3rd optional argument to event subscriptions e.g. `.on` where a timestamp can be used  to help prevent missing multi-runtime startup events
⛓ Paired with this [core PR](https://github.com/HadoukenIO/core/pull/576)
➕[New test: Multi-runtime missed events](https://testing-dashboard.openfin.co/#/app/tests/5bae247ecb360141a7dfcfab/edit)
✅ **Automated test results**
[Windows 7](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bbcf827cb360141a7dfd041)
[Windows 10](https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5bbcfea3cb360141a7dfd042)

RUN-3654 added support for event timestamps

---

test/global-hotkey.test.ts
test/interappbus.test.ts

Updates js-adapter tests for changes introduced by [this pr](https://github.com/HadoukenIO/core/pull/570)

Fixed error messages in tests

---

tutorials/System.getProxySettings.md

This PR updated the tutorial to make it consistent with APIv1.

RUN-4727 Update the tutorial for System.getProxySettings

---

src/api/application/application.ts
src/api/application/applicationOption.ts
src/api/base.ts
src/api/events/application.ts
src/api/events/base.ts
src/api/system/application.ts
src/api/system/external-process.ts
src/api/system/host-specs.ts
src/api/system/process.ts
src/api/system/proxy.ts
src/api/system/rvm.ts
src/api/system/system.ts
src/api/system/window.ts
src/api/window/anchor-type.ts
src/api/window/window.ts
src/api/window/windowOption.ts

This PR  mainly fix some shapes issues in V2.   
This is [PR for DefinitelyTyped.](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30203)

RUN-4647 definitely typed: move shapes from v1 to v2

---

Gruntfile.js
src/api/interappbus/channel/channel.ts
src/api/interappbus/channel/client.ts
src/api/interappbus/channel/index.ts
src/api/interappbus/channel/provider.ts

[Core PR](https://github.com/HadoukenIO/core/pull/613)
New Testrunner tests:
[test1](https://testing-dashboard.openfin.co/#/app/tests/5be1bffecb360141a7dfd22f/edit)
[test2](https://testing-dashboard.openfin.co/#/app/tests/5be09f96cb360141a7dfd1fc/edit)
[test3](https://testing-dashboard.openfin.co/#/app/tests/5be0a3d9cb360141a7dfd200/edit)
[test4](https://testing-dashboard.openfin.co/#/app/tests/5be0a5bfcb360141a7dfd201/edit)
[test5](https://testing-dashboard.openfin.co/#/app/tests/5be0a0facb360141a7dfd1fe/edit)
[test6](https://testing-dashboard.openfin.co/#/app/tests/5be1ac71cb360141a7dfd22a/edit)
[test7](https://testing-dashboard.openfin.co/#/app/tests/5be0acb4cb360141a7dfd202/edit)
[test8](https://testing-dashboard.openfin.co/#/app/tests/5be1e978cb360141a7dfd244/edit) …

RUN-4677 - Channel lifecycle

---

docs.README(OLD).md
docs.README.md
jsdoc-conf.json
src/api/interappbus/channel/channels-docs.ts
src/api/interappbus/interappbus.ts
tutorials/Channel.middleware.md
tutorials/Channel.onChannelConnect.md
tutorials/Channel.onChannelDisconnect.md
tutorials/Channel.tutorial.md

Kept the old readme in case we want to include that somewhere.

RUN-4827 - mostly there to parity with v1

---

Gruntfile.js
package-lock.json
package.json

ℹ️ Changes:
**Before**: 
1. Transpile everything from TS to JS 
2. Webpack for browser using transpiled JS
**Now**:
1. Webpack for browser using original TS
⛓ Goes together with [core's PR](https://github.com/HadoukenIO/core/pull/665)

RUN-4758 build fix

---

docs.README.md
src/api/events/window.ts
src/api/window/window.ts
test/window.test.ts
tutorials/Window.disableFrame.md
tutorials/Window.enableFrame.md

This PR should combine with [Core PR](https://github.com/HadoukenIO/core/pull/678)
[Add two new tests for V2API](https://testing-dashboard.openfin.co/#/app/tests)

RUN-4829 naming change from 'frame' to 'userMovement'

---

Gruntfile.js

add back webpack alias

---

docs.README.md
src/api/application/application.ts
src/transport/port-discovery.ts

This PR is fixing some miscellaneous issues found in v2API.

RUN-4833 Fix some misc known issues

---

docs.README.md
src/api/interappbus/channel/channels-docs.ts

* Still need to fill in the links for
- WindowOptions
- AppOptions
- New webpage (to be created) explaining difference between v1 and v2 APIs

RUN-4948 - V2 docs improvements

---

docs.README.md
src/api/window/window.ts
test/window.test.ts
tutorials/Window.getCurrent.md
tutorials/Window.getCurrentSync.md
tutorials/Window.isMainWindow.md

Add a new [test](https://testing-dashboard.openfin.co/#/app/tests/5c1bca1bcb360141a7dfd79a/edit) for it

RUN-4830 add isMainWindow function

---

tutorials/Application.close.md
tutorials/Application.create.md
tutorials/Application.createFromManifest.md
tutorials/Application.quit.md
tutorials/Application.run.md
tutorials/Application.start.md
tutorials/Application.startFromManifest.md

Update docs tutorials for application start and quit

RUN-4644 Updated tutorials for start + quit

---

src/shapes.ts

In the future we can co-locate these if we want. For now this will allow the first cut integration with native window APIs that are coming down the pipe shortly.
@whyn07m3

added some shapes that native window integration will need

---

src/util/http.ts
tutorials/Window.flash.md

This PR is to fix tests not running issue.

RUN-5085 Fix an unhanded Promise Rejection issue in tests

---

src/api/window/window.ts

⛓ Linked with [this core PR](https://github.com/HadoukenIO/core/pull/741)

RUN-5006 window options deep merge

---

src/api/interappbus/channel/channels-docs.ts

Broken links for ConnectOptions & ConnectionEvent

RUN-5141 - channels doc link fixes

---

src/api/application/application.ts
src/api/frame/frame.ts
src/api/interappbus/interappbus.ts
src/api/window/window.ts
src/util/validate.ts

This PR is to validate the identity object passed in IAB.send and all the wrap functions.

RUN-5140 IAB.send should return an error if the destination is not valid object

---

src/api/system/runtime-info.ts
src/api/system/system.ts
test/system.test.ts

Types and tests for [RUN-5223 added the args object to the getRuntimeInfo call ](https://github.com/HadoukenIO/core/pull/776)

updated RuntimeInfo type with the args prop

---

src/api/window/window.ts
src/api/window/windowOption.ts
src/shapes.ts

alphaMask - added to docs & types
applicationIcon - added to docs & types
contextMenuSettings - added to docs & types
taskbarIcon - added to docs & types

RUN-5249: Doc fixes

---

src/api/events/application.ts

conflict between native window and https://github.com/HadoukenIO/js-adapter/pull/279

Fix build on bounds import

---

test/launch-services.test.ts

fixed issue where services test would leave zombie processes

---

test/window.test.ts

The test tried calling navigateBack when history was empty,
I fixed that.

RUN-5060 - fixing bad test

---

src/api/external-window/external-window.ts

Jira: https://appoji.jira.com/projects/RUN/issues/RUN-5272
Related core change: https://github.com/HadoukenIO/core/pull/825

RUN-5272: Allow user code to catch NWI wrap errors

---

package-lock.json
package.json

This fixes our v2 js docs regression.
| FROM | TO |
|---|---|
| ![image](https://user-images.githubusercontent.com/5790216/59431087-06d79e80-8db2-11e9-8a48-3c66aaabc8d5.png)  | ![image](https://user-images.githubusercontent.com/5790216/59431207-47371c80-8db2-11e9-9f01-2498bdf19992.png) |

RUN-5355 js docs fix

---

src/api/events/application.ts
src/api/events/window.ts
tutorials/Application.EventEmitter.md
tutorials/System.EventEmitter.md
tutorials/Window.EventEmitter.md

Adds docs for changes in https://github.com/HadoukenIO/core/pull/854

Add performance-report docs

---

.github/PULL_REQUEST_TEMPLATE.md

Adding a PR Template with our standard checklist.
Internal, not relevant release notes.

RUN-5305 PR Template on the js-adapter repo

---

src/api/browserview/browserview.ts

Update autoresize options for v13
Notes:

updated autoresize

---

src/api/application/applicationOption.ts
src/api/external-window/external-window.ts
src/api/window/window.ts
src/api/window/windowOption.ts
src/shapes.ts

This PR is to fix a type issue in openfin DefinitelyTyped.

RUN-5240 update customeData type to any

---

package-lock.json
package.json

Version bump for NPM release.
@luiemilio please update the cli.

Publish version 1.43.1

---

src/api/external-window/external-window.ts
src/api/window/window.ts

The PR updates the docs following the changes in the core
Notes: Joining groups with external windows is currently not supported
@rdepena @datamadic

[DOCS] RUN-5470 Join Group should Nack if given an "Native Window"

---

src/launcher/services.ts

A bug-fix made on the app directory server made this necessary.  The CLI took an inadvertent dependency on a bug.
Notes: This fixes a CLI bug that only occurred on the mac (in the 'nix launcher).  The bug was introduced due to a fix to the app directory web service

RUN-5479 - fix app directory path, bug-fix in app dir made this necessary

---

src/api/window/window.ts
tutorials/Window.center.md

Add window.center API
Added API to center windows
Notes:

RUN-5475 - Add window.center API

---

src/api/frame/frame.ts

Moved doc description from javascript-adapter docs to this repo

RUN-5385 Migrate the old frame docs to the new ones

---

src/api/interappbus/channel/channels-docs.ts
tutorials/InterApplicationBus.subscribe.md

updated subscribe typo, onChannelConnect definition

---

src/api/external-window/external-window.ts
src/identity.ts
tutorials/ExternalWindow.wrap.md

Changes to support this core PR: https://github.com/HadoukenIO/core/pull/908

RUN-5493: Add nativeId to identity, upgrade tutorial

---

src/api/browserview/browserview.ts

Added BrowserView.destroy method
https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5d8002367bacba7f712054c8
Notes: na experimental

RUN-5608 added view.destroy

---

src/api/application/application.ts
src/api/browserview/browserview.ts
src/api/window/window.ts
src/transport/transport.ts

Added methods to query BrowserView State
Tests https://testing-dashboard.openfin.co/#/app/sessions/api/completed/5d7ff6957bacba7f712054bb
Notes: n/a experimental

RUN-5469 Added state methods

---

package.json

Bump to version 1.44.1

---

src/api/application/application.ts

RVM-976: createFromManifest options

---

src/api/fin.ts
src/transport/transport.ts
test/multi-runtime-utils.ts
test/uuid-enforcement.test.ts

This PR is to make electron IPC not accessible from client side APIs. 
Notes:

RUN-5530 remove access to electron ipc

---

src/api/global-hotkey/index.ts

Fixes a comment block in global hotkey api.

[N/A] Fix global hotkey api return type comment typo
